spring:
  datasource:
    url: jdbc:mysql://aquamole-db.mysql.database.azure.com:3306/aquamole
    username: aquamole_user
    password: iotuser16!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

secret:
  key: 2B4D6251655468576D5A7134743777217A25432A462D4A404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226
